language: java
matrix:
  include:
    - os: linux
      language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - build-tools-25.0.2
          - android-25
          - platform-tools-25
          - extra-android-support
          - extra-android-m2repository
          - extra-google-m2repository
        licenses:
          - '.+'
    - os: osx
      env: ANDROID_HOME=/usr/local/opt/android-sdk
      osx_image: xcode8

sudo: required

before_install: rm -rf /home/travis/.nvm

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update > /dev/null;
      brew install android-sdk nvm;
      nvm install 6;
      nvm use --delete-prefix 6;
      echo y | android --verbose update sdk --no-ui --all --filter platform-tools,build-tools-25.0.2;
      pip install virtualenv;
      elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -;
      sudo apt-get install -y python-software-properties;
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update;
      sudo apt-get install -y nodejs gcc-5 g++-5;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++ g++ /usr/bin/g++-5;
      sudo update-alternatives --set gcc /usr/bin/gcc-5;
      fi

before_script: sudo npm install -g cordova

script:
  - ./prepare.sh && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cordova prepare ios;
      cordova build ios;
      elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cordova prepare android;
      cordova build android;
      fi
