language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - platform-tools-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'
os:
  - osx
  - linux

sudo: required

before_install:
  - rm -rf /home/travis/.nvm                                         #
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -   # upgrade node manually as we're building on
  - sudo apt-get install -y nodejs                                   # android language and can't pick it in yml
  - sudo npm install -g cordova
script:
  - cordova prepare android
  - cordova compile android
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cordova prepare ios;
      cordova compile ios;
      fi
