language: java
matrix:
  include:
    - os: linux
      language: android
      android:
        components:
          - tools
          - build-tools-23.0.2
          - android-23
          - platform-tools-23
          - extra-android-support
          - extra-android-m2repository
          - extra-google-m2repository
        licenses:
          - '.+'
    - os: osx
      env: ANDROID_HOME=/usr/local/opt/android-sdk

sudo: required

before_install: rm -rf /home/travis/.nvm

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update > /dev/null;
      brew install android-sdk nodejs;
      echo y | android --verbose update sdk --no-ui --all --filter platform-tools,build-tools-23.0.2;
      elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -;
      sudo apt-get install -y nodejs;
      fi

before_script: sudo npm install -g cordova

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cordova prepare ios;
      cordova compile ios;
      elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cordova prepare android;
      cordova compile android;
      fi
